"""empty message

Revision ID: c27c81f8ea3a
Revises: 1bad900c9ee1
Create Date: 2024-05-17 05:16:49.353557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27c81f8ea3a'
down_revision = '1bad900c9ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_to_read', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('time_to_read')

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
