"""empty message

Revision ID: d166c78bebc7
Revises: c0cbefcc9625
Create Date: 2024-05-09 20:28:04.060769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd166c78bebc7'
down_revision = 'c0cbefcc9625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
